version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_EXPLORE_ENABLED=true
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-image-panel,marcusolsson-dynamictext-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-static-datasource
      - ./provisioning:/etc/grafana/provisioning
