services:
  grafana:
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_EXPLORE_ENABLED=true
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=volkovlabs-image-panel,marcusolsson-dynamictext-panel,grafana-llm-app
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-static-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=volkovlabs-image-panel,marcusolsson-dynamictext-panel,grafana-llm-app
      # - GF_FEATURE_TOGGLES_ENABLE=dashboardScene
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-static-datasource
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    network_mode: host
    profiles:
      - e2e
